// Demo data for development/preview — replaces empty states with realistic content

export const DEMO_CLIENTS = [
  {
    id: 'demo-1',
    name: 'Акрон Скрап Урал',
    domain: 'ural.akron-scrap.ru',
    website_url: 'https://ural.akron-scrap.ru',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 53,
    pages_total: 53,
    scan_phase: 'done',
    scan_quality: 65,
    needs_deep_scan: false,
    niche: 'Металлолом, промышленность',
    assistant_name: 'Алекс',
    assistant_mode: 'sales' as const,
    assistant_avatar_url: null,
    leads_used: 14,
    leads_limit: 50,
    dialogs_used: 87,
    dialogs_limit: 300,
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-05-20T15:30:00Z',
    plan: 'Новый',
    plan_color: '#10b981',
    retention_days: 13,
    monthly_revenue: 4900,
    widget_online: true,
    last_dialog_at: '2026-05-27T09:15:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-1',
    trial_active: false,
  },
  {
    id: 'demo-2',
    name: 'Платья больших размеров',
    domain: 'platya-bolshikh-razmerov.ru',
    website_url: 'https://platya-bolshikh-razmerov.ru',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 106,
    pages_total: 106,
    scan_phase: 'done',
    scan_quality: 79,
    needs_deep_scan: false,
    niche: 'Модная одежда, e-commerce',
    assistant_name: 'Вика',
    assistant_mode: 'sales' as const,
    assistant_avatar_url: null,
    leads_used: 31,
    leads_limit: 100,
    dialogs_used: 213,
    dialogs_limit: 500,
    created_at: '2026-02-28T11:00:00Z',
    updated_at: '2026-05-25T12:00:00Z',
    plan: 'Новый',
    plan_color: '#10b981',
    retention_days: 8,
    monthly_revenue: 9800,
    widget_online: true,
    last_dialog_at: '2026-05-27T10:42:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-2',
    trial_active: true,
  },
  {
    id: 'demo-3',
    name: 'ООО "АКРОН СКРАП НИЖНИЙ НОВГОРОД"',
    domain: 'nnovgorod.akron-scrap.ru',
    website_url: 'https://nnovgorod.akron-scrap.ru',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 38,
    pages_total: 38,
    scan_phase: 'done',
    scan_quality: 70,
    needs_deep_scan: false,
    niche: 'Металлолом, промышленность',
    assistant_name: 'Николай',
    assistant_mode: 'support' as const,
    assistant_avatar_url: null,
    leads_used: 12,
    leads_limit: 50,
    dialogs_used: 47,
    dialogs_limit: 200,
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-05-15T16:00:00Z',
    plan: 'Trial',
    plan_color: '#f97316',
    retention_days: 5,
    monthly_revenue: 0,
    widget_online: true,
    last_dialog_at: '2026-05-26T18:30:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-3',
    trial_active: true,
    trial_ends_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 'demo-4',
    name: 'Завод Металлических Изделий',
    domain: '1994doors.ru',
    website_url: 'https://1994doors.ru',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 29,
    pages_total: 29,
    scan_phase: 'done',
    scan_quality: 84,
    needs_deep_scan: false,
    niche: 'Металлоизделия, двери',
    assistant_name: 'Сергей',
    assistant_mode: 'sales' as const,
    assistant_avatar_url: null,
    leads_used: 7,
    leads_limit: 50,
    dialogs_used: 23,
    dialogs_limit: 200,
    created_at: '2026-04-05T14:00:00Z',
    updated_at: '2026-05-22T10:00:00Z',
    plan: 'Демонстрация',
    plan_color: '#8b5cf6',
    retention_days: 8,
    monthly_revenue: 0,
    widget_online: true,
    last_dialog_at: '2026-05-27T08:00:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-4',
    trial_active: false,
  },
  {
    id: 'demo-5',
    name: 'ЭБС',
    domain: 'ebs-moscow.su',
    website_url: 'https://ebs-moscow.su',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 77,
    pages_total: 77,
    scan_phase: 'done',
    scan_quality: 80,
    needs_deep_scan: false,
    niche: 'Безопасность, охрана',
    assistant_name: 'Игорь',
    assistant_mode: 'support' as const,
    assistant_avatar_url: null,
    leads_used: 82,
    leads_limit: 200,
    dialogs_used: 341,
    dialogs_limit: 1000,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-05-27T07:00:00Z',
    plan: 'Trial',
    plan_color: '#f97316',
    retention_days: 3,
    monthly_revenue: 0,
    widget_online: false,
    last_dialog_at: '2026-05-24T14:00:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-5',
    trial_active: true,
    trial_ends_at: '2026-09-05T00:00:00Z',
  },
  {
    id: 'demo-6',
    name: 'ООО "ГК Легенда"',
    domain: '1-leg.ru',
    website_url: 'https://1-leg.ru',
    status: 'active' as const,
    index_progress: 100,
    pages_indexed: 91,
    pages_total: 91,
    scan_phase: 'done',
    scan_quality: 84,
    needs_deep_scan: false,
    niche: 'Строительство, недвижимость',
    assistant_name: 'Андрей',
    assistant_mode: 'sales' as const,
    assistant_avatar_url: null,
    leads_used: 45,
    leads_limit: 200,
    dialogs_used: 189,
    dialogs_limit: 500,
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2026-05-20T09:00:00Z',
    plan: 'Mega AI',
    plan_color: '#6b5fd4',
    retention_days: null,
    monthly_revenue: 24900,
    widget_online: true,
    last_dialog_at: '2026-05-27T11:00:00Z',
    demo_chat_url: 'https://demo.atlasai.ru/chat/demo-6',
    trial_active: false,
  },
];

export const DEMO_LEADS = [
  {
    id: 'lead-1',
    client_id: 'demo-1',
    client_name: 'Акрон Скрап Урал',
    client_domain: 'ural.akron-scrap.ru',
    created_at: '2026-05-27T09:15:00Z',
    name: 'Михаил Петров',
    phone: '+7 (922) 123-**-**',
    phone_full: '+7 (922) 123-45-67',
    email: 'mpe***@mail.ru',
    request_text: 'Хочу сдать около 5 тонн металлолома, нужна оценка и вывоз',
    status: 'new' as const,
    priority: 'urgent' as const,
    utm_source: 'yandex',
    utm_medium: 'cpc',
    utm_campaign: 'metallolom_ural',
  },
  {
    id: 'lead-2',
    client_id: 'demo-2',
    client_name: 'Платья больших размеров',
    client_domain: 'platya-bolshikh-razmerov.ru',
    created_at: '2026-05-26T14:30:00Z',
    name: 'Анна Смирнова',
    phone: '+7 (916) 987-**-**',
    phone_full: '+7 (916) 987-65-43',
    email: 'ann***@gmail.com',
    request_text: 'Интересует платье на выпускной, размер 54, бюджет до 8000 руб',
    status: 'contacted' as const,
    priority: 'normal' as const,
    utm_source: 'vk',
    utm_medium: 'target',
    utm_campaign: 'platya_vesna',
  },
  {
    id: 'lead-3',
    client_id: 'demo-5',
    client_name: 'ЭБС',
    client_domain: 'ebs-moscow.su',
    created_at: '2026-05-25T11:00:00Z',
    name: 'Дмитрий Козлов',
    phone: '+7 (985) 456-**-**',
    phone_full: '+7 (985) 456-78-90',
    email: null,
    request_text: 'Нужна установка видеонаблюдения на склад 2000 кв.м',
    status: 'closed' as const,
    priority: 'normal' as const,
    utm_source: 'google',
    utm_medium: 'organic',
    utm_campaign: null,
  },
  {
    id: 'lead-4',
    client_id: 'demo-3',
    client_name: 'АКРОН СКРАП НН',
    client_domain: 'nnovgorod.akron-scrap.ru',
    created_at: '2026-05-27T07:45:00Z',
    name: 'Сергей Иванов',
    phone: '+7 (910) 321-**-**',
    phone_full: '+7 (910) 321-00-99',
    email: null,
    request_text: 'Есть медный лом примерно 200 кг, как принимаете?',
    status: 'new' as const,
    priority: 'normal' as const,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
  },
  {
    id: 'lead-5',
    client_id: 'demo-6',
    client_name: 'ГК Легенда',
    client_domain: '1-leg.ru',
    created_at: '2026-05-24T16:00:00Z',
    name: 'Ольга Федорова',
    phone: '+7 (903) 789-**-**',
    phone_full: '+7 (903) 789-12-34',
    email: 'olg***@yandex.ru',
    request_text: 'Хотим купить квартиру в новостройке, бюджет 7-8 млн, 2 комнаты',
    status: 'contacted' as const,
    priority: 'urgent' as const,
    utm_source: 'yandex',
    utm_medium: 'cpc',
    utm_campaign: 'kv_novostroyki',
  },
];

export const DEMO_CONVERSATIONS = [
  {
    id: 'conv-1',
    client_id: 'demo-2',
    client_name: 'Платья больших размеров',
    client_domain: 'platya-bolshikh-razmerov.ru',
    created_at: '2026-05-27T10:42:00Z',
    visitor_id: 'vis-001',
    is_lead: true,
    utm_source: 'vk',
    message_count: 8,
    preview: 'Здравствуйте! Есть ли у вас платья на свадьбу в размере 52?',
    resolved: true,
  },
  {
    id: 'conv-2',
    client_id: 'demo-1',
    client_name: 'Акрон Скрап Урал',
    client_domain: 'ural.akron-scrap.ru',
    created_at: '2026-05-27T09:15:00Z',
    visitor_id: 'vis-002',
    is_lead: true,
    utm_source: 'yandex',
    message_count: 6,
    preview: 'Добрый день, хочу узнать цену на приём черного металла',
    resolved: true,
  },
  {
    id: 'conv-3',
    client_id: 'demo-5',
    client_name: 'ЭБС',
    client_domain: 'ebs-moscow.su',
    created_at: '2026-05-26T15:20:00Z',
    visitor_id: 'vis-003',
    is_lead: false,
    utm_source: null,
    message_count: 3,
    preview: 'Сколько стоит обслуживание системы сигнализации в месяц?',
    resolved: false,
  },
  {
    id: 'conv-4',
    client_id: 'demo-6',
    client_name: 'ГК Легенда',
    client_domain: '1-leg.ru',
    created_at: '2026-05-27T11:00:00Z',
    visitor_id: 'vis-004',
    is_lead: true,
    utm_source: 'yandex',
    message_count: 12,
    preview: 'Есть ли квартиры в ЖК Легенда с отделкой ready to move?',
    resolved: true,
  },
  {
    id: 'conv-5',
    client_id: 'demo-4',
    client_name: 'Завод Металлических Изделий',
    client_domain: '1994doors.ru',
    created_at: '2026-05-26T13:00:00Z',
    visitor_id: 'vis-005',
    is_lead: false,
    utm_source: 'google',
    message_count: 4,
    preview: 'Делаете ли вы двери нестандартных размеров на заказ?',
    resolved: false,
  },
];

export const DEMO_TEAM = [
  {
    id: 'team-1',
    name: 'Игорь Ломакин',
    job_title: 'Владелец',
    email: 'lomakin.igor.st@gmail.com',
    role: 'owner' as const,
    status: 'active' as const,
    last_login: '2026-05-27T11:00:00Z',
    clients_access: 'all',
  },
  {
    id: 'team-2',
    name: 'Анастасия Шангина',
    job_title: 'Ассистент',
    email: '10nastia.shania@gmail.com',
    role: 'manager' as const,
    status: 'active' as const,
    last_login: '2026-05-26T16:00:00Z',
    clients_access: 'all',
  },
  {
    id: 'team-3',
    name: 'Мария Жиркова',
    job_title: 'РОП',
    email: 'marizhirkova@gmail.com',
    role: 'integrator' as const,
    status: 'pending' as const,
    last_login: null,
    clients_access: 'all',
  },
  {
    id: 'team-4',
    name: 'Полетаева Мария',
    job_title: 'Аккаунт-менеджер',
    email: 'poletaeva.mary96@gmail.com',
    role: 'integrator' as const,
    status: 'active' as const,
    last_login: '2026-05-25T10:00:00Z',
    clients_access: 'selected',
  },
  {
    id: 'team-5',
    name: 'Федулов Артем',
    job_title: 'Менеджер по продажам',
    email: 'mr.fedylow@gmail.com',
    role: 'sales_manager' as const,
    status: 'active' as const,
    last_login: '2026-05-27T09:30:00Z',
    clients_access: 'selected',
  },
];

export const DEMO_SUPPORT_TICKETS = [
  {
    id: 'ticket-101',
    subject: 'Отслеживание заявок',
    category: 'Общая поддержка',
    priority: 'medium' as const,
    status: 'closed' as const,
    related_client: 'ЭБС',
    updated_at: '2026-05-25T10:00:00Z',
    message: 'Как настроить уведомления о новых лидах на email?',
  },
  {
    id: 'ticket-88',
    subject: 'Подсчет лидов',
    category: 'Общая поддержка',
    priority: 'medium' as const,
    status: 'closed' as const,
    related_client: 'Акрон Скрап Урал',
    updated_at: '2026-05-21T14:00:00Z',
    message: 'Почему в отчете показывается меньше лидов, чем я вижу в уведомлениях?',
  },
  {
    id: 'ticket-81',
    subject: 'Интеграция с Calltouch',
    category: 'Feature Request',
    priority: 'high' as const,
    status: 'closed' as const,
    related_client: 'ГК Легенда',
    updated_at: '2026-05-13T09:00:00Z',
    message: 'Нужна интеграция с Calltouch для передачи лидов',
  },
  {
    id: 'ticket-75',
    subject: 'Виджет не показывается на сайте',
    category: 'Техническая поддержка',
    priority: 'high' as const,
    status: 'in_progress' as const,
    related_client: 'ЭБС',
    updated_at: '2026-05-27T08:00:00Z',
    message: 'После обновления CMS виджет перестал отображаться на мобильных устройствах',
  },
];

export const DEMO_SCANS = DEMO_CLIENTS.map(c => ({
  id: c.id,
  name: c.name,
  domain: c.domain,
  language: 'ru',
  status: 'active' as const,
  pages: c.pages_indexed,
  analyzed_at: c.updated_at,
  quality: c.scan_quality,
}));

// Partner's own widget data (for /leads, /conversations, /analytics)
export const PARTNER_WIDGET = {
  installed: true,
  site: 'atlasai.ru',
  leads: [
    {
      id: 'p-lead-1',
      created_at: '2026-05-26T11:00:00Z',
      name: 'Виталий Чернов',
      phone: '+7 (926) 111-**-**',
      phone_full: '+7 (926) 111-22-33',
      email: 'vit***@gmail.com',
      request_text: 'Хочу подключить платформу для своего агентства, 15 клиентов',
      status: 'new' as const,
      priority: 'urgent' as const,
      utm_source: 'yandex',
      utm_medium: 'cpc',
      utm_campaign: 'atlas_partners',
    },
    {
      id: 'p-lead-2',
      created_at: '2026-05-25T15:30:00Z',
      name: 'Наталья Кузнецова',
      phone: '+7 (903) 444-**-**',
      phone_full: '+7 (903) 444-55-66',
      email: 'nat***@mail.ru',
      request_text: 'Интересует тариф на 5 клиентов, нужна демонстрация',
      status: 'contacted' as const,
      priority: 'normal' as const,
      utm_source: 'vk',
      utm_medium: 'target',
      utm_campaign: null,
    },
    {
      id: 'p-lead-3',
      created_at: '2026-05-24T09:00:00Z',
      name: 'Андрей Волков',
      phone: '+7 (916) 777-**-**',
      phone_full: '+7 (916) 777-88-99',
      email: 'and***@yandex.ru',
      request_text: 'Уже использую похожий сервис, хочу сравнить цены',
      status: 'contacted' as const,
      priority: 'normal' as const,
      utm_source: null,
      utm_medium: null,
      utm_campaign: null,
    },
    {
      id: 'p-lead-4',
      created_at: '2026-05-20T14:00:00Z',
      name: 'Светлана Морозова',
      phone: '+7 (985) 222-**-**',
      phone_full: '+7 (985) 222-33-44',
      email: 'sve***@inbox.ru',
      request_text: 'Подключили, всё отлично — клиент доволен',
      status: 'closed' as const,
      priority: 'normal' as const,
      utm_source: 'organic',
      utm_medium: null,
      utm_campaign: null,
    },
  ],
  conversations: [
    {
      id: 'pc-1',
      created_at: '2026-05-27T10:00:00Z',
      visitor_id: 'pv-001',
      is_lead: true,
      utm_source: 'yandex',
      message_count: 9,
      preview: 'Добрый день! Расскажите о тарифах для агентств',
      resolved: true,
    },
    {
      id: 'pc-2',
      created_at: '2026-05-26T11:00:00Z',
      visitor_id: 'pv-002',
      is_lead: true,
      utm_source: 'vk',
      message_count: 6,
      preview: 'Сколько клиентских сайтов можно подключить к одному кабинету?',
      resolved: true,
    },
    {
      id: 'pc-3',
      created_at: '2026-05-25T16:00:00Z',
      visitor_id: 'pv-003',
      is_lead: false,
      utm_source: 'google',
      message_count: 3,
      preview: 'Есть ли бесплатный тариф для проверки?',
      resolved: false,
    },
    {
      id: 'pc-4',
      created_at: '2026-05-24T14:00:00Z',
      visitor_id: 'pv-004',
      is_lead: false,
      utm_source: null,
      message_count: 2,
      preview: 'Как быстро AI отвечает на вопросы?',
      resolved: false,
    },
    {
      id: 'pc-5',
      created_at: '2026-05-23T10:00:00Z',
      visitor_id: 'pv-005',
      is_lead: true,
      utm_source: 'telegram',
      message_count: 11,
      preview: 'Хочу купить подписку, как это сделать?',
      resolved: true,
    },
  ],
};
